language: ruby

cache: bundler

sudo: false

before_install:
  - gem update --system
  - gem install bundler

env:
  global:
    # --dev improves JRuby startup time
    # --debug reports proper coverage to SimpleCov
    # See https://github.com/jruby/jruby/wiki/Improving-startup-time
    - JRUBY_OPTS="--dev --debug"

rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - rbx-3
  - ruby-head
  - jruby-9.2.0.0

matrix:
  allow_failures:
    - rvm: rbx-3
    - rvm: ruby-head
    - rvm: jruby-9.2.0.0
  fast_finish: true
